import React from 'react';
import { useNavigate } from 'react-router-dom';
import './CreateAccount.css';
import Footer from '../../components/Footer/Footer'; 


import bgImage from '../../assets/images/background.png'; 
import buildingImg from '../../assets/images/building.png';
import infoIconPng from '../../assets/images/info-icon.png'; 
import emailIconPng from '../../assets/images/email-icon.png'; 
import phoneIconPng from '../../assets/images/phone-icon.png';
import locationIconPng from '../../assets/images/location-icon.png';
import returnArrowPng from '../../assets/images/return-arrow.png';
import mailIconPng from '../../assets/images/mail-icon.png';  

const CreateAccount = () => {
  const navigate = useNavigate();

  return (
  
    <div className="reset-screen">
     
      <div className="background-container">
        <img src={bgImage} alt="background" className="bg-image" />
      </div>

      <div className="activate-main-content"> 
        <div className="activate-card">
          <div className="card-header">
            <img src={buildingImg} alt="University Building" className="header-image" />
          </div>

          <div className="card-body">
            <h2>Activate Your Account</h2>
            <p className="description">
              CampusHub accounts are automatically generated by the University Administration upon enrollment or hiring. We do not offer manual registration at this time.
            </p>

            
            <div className="info-box">
              <img src={infoIconPng} alt="Info" className="info-png-icon" />
              <p>If you haven't received your credentials via your official university email, please reach out to the IT department for assistance.</p>
            </div>

            <div className="contact-section">
              <p>DIRECT CONTACT INFORMATION</p>
              
              
              <div className="contact-card">
                <img src={mailIconPng} alt="Email" className="contact-card-icon" />
                <span className="label">Email Support</span>
                <span className="value blue-text">support@campushub.edu</span>
              </div>

              <div className="contact-card">
                <img src={phoneIconPng} alt="Phone" className="contact-card-icon" />
                <span className="label">Phone Support</span>
                <span className="value">(555) 123-4567</span>
              </div>

              <div className="contact-card">
                <img src={locationIconPng} alt="Location" className="contact-card-icon" />
                <span className="label">IT Desk Location</span>
                <span className="value">Library, 2nd Floor</span>
              </div>
            </div>

            
            <a href="mailto:support@campushub.edu?subject=Account Activation Assistance&body=Hello IT Team, I need help with my account activation." className="email-link-wrapper">
              <button className="email-btn">
                <img src={emailIconPng} alt="Email" className="btn-png-icon white-icon" /> 
                Email IT Support
              </button>
            </a>

            <div className="return-container">
              <img src={returnArrowPng} alt="Return" className="return-png-icon" /> 
              <button className="back-to-login" onClick={() => navigate('/')}>
                Return to Login
              </button>
            </div>
          </div>
        </div>
      </div>

      <Footer /> 
    </div>
  );
};

export default CreateAccount;